version: "3"

volumes:
    prometheus_data: {}
    grafana_data: {}

services:

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
      - "./config:/config"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    expose:
      - 9090
    ports: 
      - 9090:9090
    links:
      - blackbox_exporter

  blackbox_exporter:
    image: prom/blackbox-exporter
    ports:
      - 9115:9115
    dns: 8.8.8.8
    restart: always
    ports:
      - 9115:9115
    expose: 
      - 9115
    volumes:
      - "./config:/config"
    command: --config.file=/config/blackbox.yml

  node-exporter:
      image: prom/node-exporter:latest  #v0.18.1
      container_name: nodeexporter
      restart: unless-stopped
      expose:
        - 9100
      ports: 
        - 9100:9100


  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    restart: unless-stopped
    privileged: true            ##
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    expose:
      - 8080


  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    links:
      - prometheus:prometheus
    ports:
      - 9000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring     # Login credentials (.gitignore)




