# my global config
global:
  scrape_interval:     5s # By default, scrape targets every 15 seconds.
  evaluation_interval: 5s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'my-project'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  # - "alert.rules"
  # - "first.rules"
  # - "second.rules"



scrape_configs:
  - job_name: 'nodeexporter'  # Metrics fra maskiner
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.131.26:9100', '192.168.133.49:9100', '192.168.131.208:9100']  
# server1: 192.168.131.26, server2: 192.168.133.49, server3: 192.168.131.208

  - job_name: 'cadvisor'      # Metrics fra containere
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx] # Look for a HTTP 200 response.
    file_sd_configs:
      - files: ['/config/blackbox_targets.yml']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: monitoring_blackbox_exporter_1:9115